### ISSUE TITLE
problem installing Annotald

### ISSUE THREAD

**Issue by abreitba** [Annotald/annotald#87]
I have a problem installing Annotald on an iMac (MacOS Sierra 10.12.2). I have Python 2.7.13 installed, besides Python 3.5.
I tried "sudo -H pip install annotald​", and this happens - what could be the problem? Thank you!

```
Collecting annotald
  Downloading annotald-1.3.8-py2.py3-none-any.whl (196kB)
    100% |████████████████████████████████| 204kB 857kB/s 
Collecting argparse (from annotald)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting mako (from annotald)
  Downloading Mako-1.0.6.tar.gz (575kB)
    100% |████████████████████████████████| 583kB 1.3MB/s 
Collecting cherrypy (from annotald)
  Downloading CherryPy-8.7.0-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 471kB 1.5MB/s 
Collecting nltk==2.0.5 (from annotald)
  Downloading nltk-2.0.5.tar.gz (954kB)
    100% |████████████████████████████████| 962kB 831kB/s 
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpzrgg_dk3
    Traceback (most recent call last):
      File "/private/tmp/pip-build-rwy92b7l/nltk/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-rwy92b7l/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/private/tmp/pip-build-rwy92b7l/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/tmp/pip-build-rwy92b7l/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/tmp/pip-build-rwy92b7l/nltk/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/private/tmp/pip-build-rwy92b7l/nltk/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-rwy92b7l/nltk/
```

**Comment by aecay** [comment]
I think this results from using a `pip` that is associated with a python 3 installation.  Annotald requires python 2.  You can check which version of python pip sees with the command `pip --version`.  Depending on how python is installed, the command to access pip under python 2 may be named `pip2`, so you can try `sudo -H pip2 install annotald​`

**Comment by abreitba** [comment]
Hi Aaron,

thanks a lot, that was it!

All best,
Anne
