### ISSUE TITLE
Annotald install failure

### ISSUE THREAD

**Issue by cathy0623** [Annotald/annotald#93]
Hi! I tried to install Annotald with MacBook Pro and it has macOS High Sierra 10.13.5. When using terminal to install annotald, it always reports like:

Collecting annotald
  Using cached https://files.pythonhosted.org/packages/ab/d4/8483768b5ccef10578415afaf4e0e612ac1a9c09731e346fcda1d0cd06c5/annotald-1.3.8-py2.py3-none-any.whl
Requirement already satisfied: mako in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Mako-1.0.7-py2.7.egg (from annotald) (1.0.7)
Requirement already satisfied: cherrypy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/CherryPy-16.0.2-py2.7.egg (from annotald) (16.0.2)
Requirement already satisfied: argparse in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/argparse-1.4.0-py2.7.egg (from annotald) (1.4.0)
Collecting nltk==2.0.5 (from annotald)
  Using cached https://files.pythonhosted.org/packages/50/9e/39418026bf8013bbc2852c7aec3fb21e4339f6cd694934496d67a19b53b8/nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p7/x8lxdzb13xb8f0p2l8911plm0000gn/T/pip-install-Nc85LA/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/p7/x8lxdzb13xb8f0p2l8911plm0000gn/T/pip-install-Nc85LA/nltk/

It seems like nltk is having problem but I am having the latest version of nltk (3.2.5) and I also have python 2.7, I also met the problem that I could not find ez_setup.py in my computer...

Hoping to hearing from you soon!!

**Comment by rtruswell** [comment]
Same issue, macos 10.13.6.  It's apparently caused by a dependency on a specific version of NLTK (compare output for "pip install nltk" with "pip install nltk==2.0.5").

For now, it seems you can still install versions of annotald up to 1.3 ("pip install annotald==1.3").  I can, at least -- would be interested to hear if anyone else gets anywhere with this.

**Comment by aecay** [comment]
Please try to install annotald again.  I have created a new version (1.3.10) which resolves these installation errors.
