### ISSUE TITLE
Annotald install error

### ISSUE THREAD

**Issue by hannahbooth** [Annotald/annotald#95]
Hi, I am trying to install Annotald on macOS High Sierra 10.13.6. I have Python 2.7.13 installed. When I do "sudo -H pip install annotald" I get the following error. Can anyone help? Many thanks!

Collecting annotald
  Using cached https://files.pythonhosted.org/packages/bf/ef/679c7d1d6e7d3cd8dc97d4d692dd2d4047fbe8c6d945b909069a2fd7a29f/annotald-1.3.10.tar.gz
Requirement already satisfied: mako in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from annotald) (1.0.7)
Requirement already satisfied: cherrypy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from annotald) (17.4.1)
Requirement already satisfied: argparse in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from annotald) (1.4.0)
Collecting nltk2-fixed==2.0.6 (from annotald)
  Using cached https://files.pythonhosted.org/packages/c3/96/761a4fb63a84a78a50d29072735168ca2b8ffdf47c38367bba35482583e6/nltk2-fixed-2.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading https://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-TrodqA/nltk2-fixed/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
        context=self._context)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-TrodqA/nltk2-fixed/

**Comment by MathieuGoux** [comment]
Some years later...

I encounter the exact same problem. After some try, I find this fix :

https://timonweb.com/python/fixing-certificate_verify_failed-error-when-trying-requests-html-out-on-mac/

Just try these command (first one, then the other) :

pip install --upgrade certifi

open /Applications/Python\ 3.6/Install\ Certificates.command

Then try the installation again. It should work!

**Comment by MathieuGoux** [comment]
> 
> 
> Some years later...
> 
> I encounter the exact same problem. After some try, I find this fix :
> 
> https://timonweb.com/python/fixing-certificate_verify_failed-error-when-trying-requests-html-out-on-mac/
> 
> Just try these command (first one, then the other) :
> 
> pip install --upgrade certifi
> 
> open /Applications/Python\ X.X/Install\ Certificates.command
> 
> Then try the installation again. It should work!

(On the second command, be carefrul of the Python version: change 3.6 to 2.7 if needed to, or use the autocompletion feature
