### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by catarinamagro** [Annotald/annotald#96]
I just installed Annotald on a new MacBook Pro, but I can't make it work. The relevant data is as follows:

operating system: macOS Mojave 10.14.6
python version (pre-installed): 2.7.10
pip command: 6.1.1 from /Library/Python/2.7/site-packages
annotald: installed to /usr/local/bin
error message: 

MacBook-Pro-de-informatica:bin cmagro$ annotald /Users/cmagro/Documents/CLUL/anotacao/textos_ps/xix/CARDS0001.psd 
Traceback (most recent call last):
  File "/usr/local/bin/annotald", line 14, in <module>
    import annotald.treedrawing
  File "/Library/Python/2.7/site-packages/annotald/treedrawing.py", line 39, in <module>
    import cherrypy
  File "/Library/Python/2.7/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/Library/Python/2.7/site-packages/cherrypy/_cperror.py", line 123, in <module>
    import urllib.parse
ImportError: No module named parse

Could anyone help me?

**Comment by aecay** [comment]
Please enter the following commands:
```
sudo pip uninstll cherrypy
sudo pip install "cherrypy<18"
```

And try annotald again.  This should fix your problem, but please let me know if it does not.

**Comment by catarinamagro** [comment]
Thank you for your prompt answer. Now I get a different error message:

Traceback (most recent call last):
  File "/usr/local/bin/annotald", line 14, in <module>
    import annotald.treedrawing
  File "/Library/Python/2.7/site-packages/annotald/treedrawing.py", line 39, in <module>
    import cherrypy
  File "/Library/Python/2.7/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/Library/Python/2.7/site-packages/cherrypy/_cperror.py", line 129, in <module>
    from more_itertools import always_iterable
  File "/Library/Python/2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/Library/Python/2.7/site-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

**Comment by aecay** [comment]
You will need to try the following commands:

```
sudo pip uninstall more_itertools
sudo pip install "more_itertools<6"
```

Python 2.7 is a very old version, and it will stop being supported on Dec 31.  I will see if I can find time before then to migrate to Python 3 and fix these and similar issues.

**Comment by catarinamagro** [comment]
Thank you very much for your help, Aaron. The problem is solved for now! When you migrate to Python 3, please let me know.

**Comment by cdsapp** [comment]
@aecay migrating to Python 3 would be great. We keep running into invalid certificate issues whenever we install annotald on a new machine.
